### ISSUE TITLE
[Server] Kontrola wysyłania i czytania wiadomości

### ISSUE THREAD

**Issue by tmurawsk** [kamdibus/TIN#6]
Funkcja write() nie powinna wywoływać się sama (bo zawiesza wątek i nie ma jak jej przerwać). Należy to rozwiązać stosując jedno z poniższych rozwiązań:
- użycie funkcji **select()** przed write()
- użycie mechanizmu **Cancellation Point** (według prowadzącego może być łatwiejsze)

Wiadomości powinny składać się z **ramek**, choćby takich prostych jak [size][----------data----------], gdzie `size` to 4-bajtowy nagłówek zawierający rozmiar danych, jakie są z nim przesyłane, a `data` to owe dane o długości `size` bajtów.

W świetle ww. zmian, powinny powstać osobne funkcje **write_n** i **read_n**, które będą czytały podane `size` bajtów. W takim wypadku komunikacja będzie wyglądała następująco:
1. Odczytaj 4 bajty nagłówka (`size`)
2. Odczytaj `size` kolejnych bajtów (`date`)

[UPDATE 16.05.2018]
Ramki najniższej warstwy są zrobione, przy czym na razie jest to zwykły rozmiar - wiadomość przesyłane clear textem. W miarę dodawania kolejnych warstw programu należy dodawać kolejne ramki.
Niemniej jednak najniższa warstwa spełnia swoje zadanie, więc zamykam issue.

**Comment by kamdibus** [comment]
Czy to nie jest tak, że wielkość przesyłanych wiadomości jest definiowana jako wielkość bufora socketu?

**Comment by tmurawsk** [comment]
Nie do końca, wiadomość jako całość może być dłuższa - np. przesyłamy plik zajmujący 2MB, ale rozmiar naszego bufora to 512B.
Chyba że ustalimy wielkość bufora równą naszemu ograniczeniu rozmiaru wiadomości, bo zdaje się, że jakieś daliśmy w dokumentacji, ale wtedy duży wyjdzie ten bufor, bo to było kilka mega.
